
describe('Register', () => {
    beforeEach(() => {
        cy.viewport(1558, 1080)
    })

    it('check UI', () => {
        cy.visit('https://flowaccount.com/')
        cy.get('.flowbtn.app-btn').click()
        cy.wait(3000)
        cy.get('.headerdiv.text-center.clearfix').find('img').should('have.attr', 'src')&&('/images/share/FlowAccount_Logo.svg')
        cy.wait(3000)
        cy.get('.welcome-wording').contains("สมัครใช้งานฟรี!")
        cy.get('.sub-welcome-wording').contains("ใช้งานได้ครบทุกฟังก์ชั่น ไม่ต้องใช้บัตรเครดิต")
        cy.get('.align-form-input').contains("อีเมล")
        cy.get('#Email').invoke('attr', 'placeholder').should('contain', 'name@example.com')
        cy.get('.align-form-input').contains("รหัสผ่าน")
        cy.get('#Password').invoke('attr', 'placeholder').should('contain', 'กรอกรหัสผ่านอย่างน้อย 8 ตัวอักษร')
        cy.get('#psruletext').contains("รหัสผ่านควรมีทั้งตัวอักษร ตัวเลข และสัญลักษณ์ผสมกัน")
        cy.get('.align-form-input').contains("เบอร์โทรศัพท์")
        cy.get('#Phone').invoke('attr', 'placeholder').should('contain', '09XXXXXXXX')
        cy.get('.control.control--checkbox').contains('คุณได้อ่านและยอมรับ')
        cy.get('.blue-line').contains('เงื่อนไขการใช้บริการ')
        cy.get('.blue-line').contains('นโยบายความเป็นส่วนตัว')
        cy.get('.login-lbl').contains('รับสิทธิ์ทดลองใช้งานฟรี')
        cy.get('.align-under-login.text-center.font_CSChatThaiUI').contains('มีบัญชีกับเราแล้ว?')
        cy.get('.blue-line').contains('ล็อกอินเข้าสู่ระบบ')
        cy.get('.none-btn.float-left.facebook').find('img').should('have.attr', 'src', '/images/social/btn_facebook_login.png')
        cy.get('.none-btn.float-right.google').find('img').should('have.attr','src','/images/share/SocialLogin_Google.png')
})

    it('check link "เงื่อนไขการใช้บริการ"',()=>{
        cy.visit('https://flowaccount.com/')
        cy.get('.flowbtn.app-btn').click()
        cy.wait(3000)
        cy.get('.blue-line').contains('เงื่อนไขการใช้บริการ').should('have.attr','href','https://flowaccount.com/term-of-use')
    })

    it('check link "นโยบายความเป็นส่วนตัว"',()=>{
        cy.visit('https://flowaccount.com/')
        cy.get('.flowbtn.app-btn').click()
        cy.wait(3000)
        cy.get('.blue-line').contains('นโยบายความเป็นส่วนตัว').should('have.attr','href','https://flowaccount.com/privacy-statement')
    })
    it('check link "ล๊อคอินเข้าสู่ระบบ"',() =>{
        cy.visit('https://flowaccount.com/')
        cy.get('.flowbtn.app-btn').click()
        cy.wait(3000)
        cy.get('.blue-line').contains("ล็อกอินเข้าสู่ระบบ").click()

    })

    it('case Register by email null', () => {
      cy.visit('https://flowaccount.com/')
      cy.get('.flowbtn.app-btn').click()
      cy.get('#Password').type('saraitest#3') 
      cy.get('#Phone').type('0627860000')
      cy.get('.control__indicator').click()
      cy.get('.signup-btn.btn-green').click()
      cy.wait(5000) 
      cy.get('#Email-error').contains('กรุณากรอกอีเมล')
      cy.wait(5000)
    })

    it('case Register by email invalid', () => {
        cy.visit('https://flowaccount.com/')
        cy.get('.flowbtn.app-btn').click()
        cy.get('#Email').type('XX') 
        cy.get('#Password').type('saraitest#3') 
        cy.get('#Phone').type('0627860000')
        cy.get('.control__indicator').click()
        cy.get('.signup-btn.btn-green').click()
        cy.wait(5000) 
        cy.get('#Email-error').contains('กรุณากรอกอีเมลให้ถูกต้อง')
        cy.wait(5000)
      })

      it('case Register by password is null', () => {
        cy.visit('https://flowaccount.com/')
        cy.get('.flowbtn.app-btn').click()
        cy.get('#Email').type('QA_test@gmail.com') 
        cy.get('#Phone').type('0627860000')
        cy.get('.control__indicator').click()
        cy.get('.signup-btn.btn-green').click()
        cy.wait(5000) 
        cy.get('#Password-error').contains('กรุณากรอกรหัสผ่าน')
        cy.wait(5000)
      })

      it('case Register by password less8character', () => {
        cy.visit('https://flowaccount.com/')
        cy.get('.flowbtn.app-btn').click()
        cy.get('#Email').type('QA_test@gmail.com') 
        cy.get('#Password').type('06') 
        cy.get('#Phone').type('0627860011')
        cy.get('.control__indicator').click()
        cy.get('.signup-btn.btn-green').click()
        cy.wait(5000) 
        cy.get('#pswmeter-message').contains('รหัสผ่านต้องมีอย่างน้อย 8 ตัว')
        cy.wait(5000)
      })
      it('case Register by phone is null', () => {
        cy.visit('https://flowaccount.com/')
        cy.get('.flowbtn.app-btn').click()
        cy.get('#Email').type('QA_test@gmail.com') 
        cy.get('#Password').type('yesy12345') 
        cy.get('.control__indicator').click()
        cy.get('.signup-btn.btn-green').click()
        cy.wait(5000) 
        cy.get('#Phone-error').contains('กรุณากรอกเบอร์โทรศัพท์')
        cy.wait(5000)
      })

      it('case Register by phone less8charecter', () => {
        cy.visit('https://flowaccount.com/')
        cy.get('.flowbtn.app-btn').click()
        cy.get('#Email').type('QA_test@gmail.com') 
        cy.get('#Password').type('yesy12345') 
        cy.get('#Phone').type('062')
        cy.get('.control__indicator').click()
        cy.get('.signup-btn.btn-green').click()
        cy.wait(5000) 
        cy.get('#Phone-error').contains('กรุณากรอกเบอร์โทรศัพท์ให้ถูกต้อง')
        cy.wait(5000)
      })

      it('case Register by data is null', () => {
        cy.visit('https://flowaccount.com/')
        cy.get('.flowbtn.app-btn').click()
        cy.get('.control__indicator').click()
        cy.get('.signup-btn.btn-green').click()
        cy.wait(5000) 
        cy.get('#Email-error').contains('กรุณากรอกอีเมล')
        cy.get('#Password-error').contains('กรุณากรอกรหัสผ่าน')
        cy.get('#Phone-error').contains('กรุณากรอกเบอร์โทรศัพท์')
        cy.wait(5000)
      })
      it('case Register Success', () => {
              cy.visit('https://flowaccount.com/')
            })
            it('sign up', () => {
                cy.get('.flowbtn.app-btn').click()
            })
            it('input data for signup' , () =>{
                cy.get('#Email').type('sarai_so1@flowaccount.com') 
                cy.get('#Password').type('saraitest#3') 
                cy.get('#Phone').type('0627860000')
                cy.get('.control__indicator').click()
                cy.get('.signup-btn.btn-green').click()
                cy.wait(10000)
})
})
